const cases = {
  resume:{targetLabel:'目标要求',target:'能定位用户流失，设计引导方案，并定义验证指标。',before:['做了新用户引导优化。','主要负责需求和验收，','转化率从32%到了46%。'],after:['针对首次创建项目的流失，','将引导拆为三步，负责方案、需求与验收；','上线前后24小时完成率32% → 46%，','增加14个百分点。（模拟）'],scene:'求职简历'},
  interview:{targetLabel:'面试关注',target:'为什么这样设计？你负责什么？结果由什么证据支持？',before:['做了新用户引导优化。','主要负责需求和验收，','转化率从32%到了46%。'],after:['我提出三步引导，负责需求与验收。','两期各观察1,000名新用户，','24小时完成率由32%变为46%。','这是前后对比，尚未验证因果。（模拟）'],scene:'求职面试'},
  promotion:{targetLabel:'示范论证方向',target:'说明业务判断、个人交付和团队结果；实际晋升还需组织职级标准。',before:['做了新用户引导优化。','主要负责需求和验收，','转化率从32%到了46%。'],after:['针对关键动作流失提出三步引导，','个人交付是方案、需求与验收。','团队观察结果为32% → 46%；','职级标准与独立归因仍需补证。（模拟）'],scene:'晋升答辩'}
};
const tabs=Array.from(document.querySelectorAll('[data-case]'));
function renderLines(id,lines){const target=document.getElementById(id);target.replaceChildren();lines.forEach((line,index)=>{if(index)target.append(document.createElement('br'));target.append(document.createTextNode(line));});}
function setPrompt(scene){document.getElementById('startup-prompt').textContent='使用 $target-jd-blueprint。\n场景：'+scene+'。\n我会提供目标 JD/晋升标准、一个真实项目与现有证据，可以包含 PDF。\n请先分析目标能力，再还原项目、核对个人贡献和结果，推荐合适写法。\n先给我项目地图、表达草稿和最重要的待补项。没有依据的数字或经历请保留为未知。\n请输出 PDF，并保留同内容的 Markdown。';document.getElementById('copy-status').textContent='复制后粘贴到 Codex 新对话，附上材料即可。';}
function activate(tab){tabs.forEach(item=>{item.setAttribute('aria-selected',String(item===tab));item.tabIndex=item===tab?0:-1;});document.getElementById('case-panel').setAttribute('aria-labelledby',tab.id);const item=cases[tab.dataset.case];renderLines('case-before',item.before);renderLines('case-after',item.after);document.getElementById('target-label').textContent=item.targetLabel;document.getElementById('target-description').textContent=item.target;setPrompt(item.scene);}
tabs.forEach(tab=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',event=>{let index=tabs.indexOf(tab);if(event.key==='ArrowRight')index=(index+1)%tabs.length;else if(event.key==='ArrowLeft')index=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')index=0;else if(event.key==='End')index=tabs.length-1;else return;event.preventDefault();tabs[index].focus();activate(tabs[index]);});});
document.getElementById('copy-prompt').addEventListener('click',async()=>{const button=document.getElementById('copy-prompt');try{await navigator.clipboard.writeText(document.getElementById('startup-prompt').textContent);button.textContent='已复制';document.getElementById('copy-status').textContent='启动指令已复制。粘贴到 Codex 新对话，并附上你的材料。';}catch{document.getElementById('copy-status').textContent='自动复制未完成，请手动选择上方指令并复制。';}window.setTimeout(()=>{button.textContent='复制指令';},2000);});
